# Use the official Node.js image as the base image
FROM node:18-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and yarn.lock (or package-lock.json)
COPY package.json ./

# Install dependencies
RUN yarn install

# Copy the rest of the application files
COPY . .

# Expose the port Next.js runs on
EXPOSE 3001

# Start the application in development mode
CMD ["yarn", "dev"]