import { ApolloProviderWrapper } from '@/apollo';
import { Toaster } from '@/components/ui/toaster';
import { DialogProvider } from '@/providers/DialogProvider';
import { TokenProvider } from '@/providers/TokenContext';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { ReactNode } from 'react';
import './globals.css';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ApolloProviderWrapper>
          <TokenProvider>
            <DialogProvider>{children}</DialogProvider>
          </TokenProvider>
          <Toaster />
        </ApolloProviderWrapper>
      </body>
    </html>
  );
}
